name: Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: var
        run: echo "commit_hash=${GITHUB_SHA:0:7}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: AMap ${{ env.commit_hash }}
          path: build/libs/